syntax enable
set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab
set smartindent
set nu rnu
set nowrap
set backspace=indent,eol,start
set guifont=Consolas:h20
map <F9> :w <CR> :!g++ -Wall -Wextra -Wpedantic -Wshadow -Wfloat-equal -Wconversion -D_DEBUG -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC % -o %:r.exe <CR>
map <F1> :!%:r.exe <CR>
